name: FlutterAppLocalizationProvider
description: A new Flutter App Localization Demo Project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
